[tool.black]
use-tabs = true
safe = true
line-length = 110
target-version = ["py37", "py38"]
exclude = '(/(\.eggs|\.git|\.mypy_cache|\.tox|\.venv|build|dist)|__pycache__)'
include = '/((mapper|tests).*\.py|pyinstaller_windows.spec|start.py)$'
